Amplicon
ENPICOM/InSilicoSeq pull request #2
Opened 2021-10-25 07:44 UTC by tessad

Added option for amplicon sequencing and for selecting a different quality bin

2021-10-25 07:53 UTC, ThijsMaas requested changes
Some small changes are required. I think it would be best to separate our changes to the quality bins, from the addition to amplicon read generation, because there are not related.

2021-10-25 07:53 UTC, ThijsMaas commented on iss/error_models/kde.py
> +                    raise ValueError('Error: the model doesn\'t contain any cdfs.')
I would use double quotes `"` here, so you won't have to escape the quote char in the string. This is also recommended by the PEP8 guidelines: https://www.python.org/dev/peps/pep-0008/#id23

2021-10-25 07:53 UTC, ThijsMaas commented on iss/error_models/kde.py
> +                start_bin = quality_bin
While we are not sure what the quality bins are used for, or if we need to improve/remove them, we should probably not touch this part of the code. Maybe we can make a separate PR for the quality bins improvement and have this PR contains only the amplicon generation part.

2021-10-25 07:53 UTC, ThijsMaas commented on iss/generator.py
>      except AssertionError as e:
I know you didn't write all of this, but this is now a weird flow. This `try except` construct can be removed if you change the `assert` statement to a simple `if` I think?

2021-10-25 07:53 UTC, ThijsMaas commented on iss/generator.py
> +            Seq(rev_comp(str(sequence[reverse_start:reverse_end+1]))),
I don't like this flow of giving the `reverse_end` a -1 and a +1. Is this done because of the assertion? And how does this affect the `bounds` parameter? In the metagenomis flow, the `bounds` will always be one shorter right now.

If you can change this so we only have to write the `reverse = SeqRecord()` line once, it will be much cleaner.

2021-10-25 07:56 UTC, ThijsMaas commented
Also, we will need to make sure the current tests are still working, and we will need to add some to test the new functionality. Have a look in the tests directory to see the test structure and think about some things we can add. I'm you are not sure, just ask ;)

2021-10-29 17:22 UTC, tessad commented
Addressed previous comments.

2022-02-16 16:17 UTC, ThijsMaas commented
Looks good!

2022-02-16 16:18 UTC, merged